services:
  db:
    image: postgres:13.10
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./go_service
    restart: on-failure:3
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_started

  client:
    build: ./js_service
    restart: on-failure:3
    depends_on:
      server:
        condition: service_started

    ports:
      - "3000:3000"


volumes:
  pg_data: